LineLength:
  Enabled: no
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
MethodLength:
  Enabled: no
Metrics/ClassLength:
  Enabled: no
Metrics/CyclomaticComplexity:
  Enabled: no
Metrics/LineLength:
  Enabled: no
Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: yes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
